### ISSUE TITLE
Exception displaying action bar

### ISSUE THREAD

**Issue by phemmer** [PyvesB/PetMaster#34]
An exception is thrown trying to display the action bar message for pet ownership.
```
[15:05:02 WARN]: [PetMaster] Errors while trying to display action bar message for pet ownership.
```

When I disable the exception handler that discards it, I receive:
```
[15:15:07 ERROR]: Could not pass event PlayerInteractEntityEvent to PetMaster v1.10.2
java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R1.PacketPlayOutChat.<init>(net.minecraft.server.v1_16_R1.IChatBaseComponent, net.minecraft.server.v1_16_R1.ChatMessageType)
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_232b09]
	at java.lang.Class.getConstructor(Class.java:1825) ~[?:1.8.0_232b09]
	at com.hm.petmaster.particle.FancyMessageSender.sendChatPacket(FancyMessageSender.java:220) ~[?:?]
	at com.hm.petmaster.particle.FancyMessageSender.sendActionBarMessage(FancyMessageSender.java:75) ~[?:?]
	at com.hm.petmaster.listener.PlayerInteractListener.displayHologramAndMessage(PlayerInteractListener.java:286) ~[?:?]
	at com.hm.petmaster.listener.PlayerInteractListener.onPlayerInteractEntityEvent(PlayerInteractListener.java:136) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor160.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-24]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-24]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-24]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-24]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2082) ~[patched_1.16.1.jar:git-Paper-24]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:49) ~[patched_1.16.1.jar:git-Paper-24]
	at net.minecraft.server.v1_16_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.16.1.jar:git-Paper-24]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-24]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-24]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-24]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-24]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-24]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136) ~[patched_1.16.1.jar:git-Paper-24]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.1.jar:git-Paper-24]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-24]
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1203) ~[patched_1.16.1.jar:git-Paper-24]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-24]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232b09]

```

This is on version 1.16, though I do not know if the issue is version dependent, as I've never tried using the plugin before.

**Comment by PyvesB** [comment]
Hello @phemmer, bumping the MCShared version as in https://github.com/PyvesB/AdvancedAchievements/commit/e754f1388bd9f62384e149f99b3f8bc04ee5d9da should do the trick. 😉
