### ISSUE TITLE
Own pet can be hurt (error console)

### ISSUE THREAD

**Issue by noircc** [PyvesB/PetMaster#39]
Hello,

Other player can hurt other pet (own by other player), and when they're doing it i've this in console : 

```
[09:27:01 ERROR]: Could not pass event EntityDamageByEntityEvent to PetMaster v1.11.0
 java.lang.NoClassDefFoundError: org/bukkit/entity/Mob
        at com.hm.petmaster.listener.PlayerAttackListener.isDamagedTargettingDamager(PlayerAttackListener.java:66) ~[?:?]
        at com.hm.petmaster.listener.PlayerAttackListener.onPlayerDamagePet(PlayerAttackListener.java:49) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor297.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:61) ~[EventExecutor.class:1.12.2-ce4aee7]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[TimedEventExecutor.class:1.12.2-ce4aee7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[RegisteredListener.class:1.12.2-ce4aee7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) ~[SimplePluginManager.class:1.12.2-ce4aee7]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:189) ~[CraftEventFactory.class:1.12.2-ce4aee7]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:715) ~[CraftEventFactory.class:1.12.2-ce4aee7]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:586) ~[CraftEventFactory.class:1.12.2-ce4aee7]
        at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:745) ~[CraftEventFactory.class:1.12.2-ce4aee7]
        at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBase.java:1643) ~[vp.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1050) ~[vp.class:?]
        at net.minecraft.entity.passive.AbstractHorse.func_70097_a(AbstractHorse.java:239) ~[aao.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1418) ~[aed.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1696) ~[oq.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1825) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) ~[li.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) ~[li.class:?]
        at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:16) ~[hv.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_211]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:839) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:470) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Mob
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:89) ~[PluginClassLoader.class:1.12.2-ce4aee7]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:76) ~[PluginClassLoader.class:1.12.2-ce4aee7]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        ... 28 more
```

Minecraft version: `git-Mohist-1.12.2-ce4aee7 (MC: 1.12.2)`
Pet Master : `1.11.0`
config.yml : `disablePlayerDamage: true`

Thanks

**Comment by PyvesB** [comment]
Hello @noircc, 

Thanks for reporting, I'll look into it. :wink:

**Comment by PyvesB** [comment]
Hopefully fixed in linked commit, will release soon!
